version: "3.6"

networks:
  wordpress-default:
    name: wordpress-default
    external: true

services:
  webserver:
    image: nginx:1.19-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_webserver
    volumes:
      - ./config/nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ${NGINX_LOG_DIR:-./logs/nginx}:/var/log/nginx:rw
      - ./config/php/phpinfo.php:/var/www/html/phpinfo.php:rw
      - ${WORDPRESS_DATA_DIR:-./wordpress}:/var/www/html
    ports:
      - "80"
      - "443"
      # - "3306"
      # - "${PHPMYADMIN_PORT}"
      - "9001"
      - "9003"
#      - "9000"
    restart: unless-stopped
    networks:
      - wordpress-default
    depends_on:
      - wordpress
    extra_hosts:
      - "host-gateway.docker.internal:host-gateway"
#    command: envsubst '${API_HOST} ${API_PORT}' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf

  wordpress:
    build:
      context: .
      dockerfile: dockerfile-php
      args:
        imgName: ${WORDPRESS_VERSION:-latest}
      labels:
        - "name=wordpress:${WORDPRESS_VERSION:-latest}-xdebug"
      network: wordpress-default
    container_name: ${COMPOSE_PROJECT_NAME}_wordpress
    user: "${CURRENT_UID}:${CURRENT_GID}"
    volumes:
      - ./config/php/php.conf.ini:/usr/local/etc/php/conf.d/php.ini
      - ./config/php/docker-xdebug.ini:/usr/local/etc/php/conf.d/docker-xdebug.ini
      - ./logs/php/php_errors.log:/var/log/php/php_errors.log
      - ./logs/php/xdebug.log:/var/log/php/xdebug.log
      - ./profiling:/tmp/profiling
      - ./config/php/phpinfo.php:/var/www/html/phpinfo.php
      - ${WORDPRESS_DATA_DIR:-./wordpress}:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=${COMPOSE_PROJECT_NAME:-wordpress}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX:-wp_}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST:-database}
      - WORDPRESS_DB_USER=${DATABASE_USER:-root}
      - WORDPRESS_DB_PASSWORD=${DATABASE_PASSWORD:-password}
      - PHP_IDE_CONFIG=serverName=docker-${COMPOSE_PROJECT_NAME}
      - SERVER_NAME=${COMPOSE_PROJECT_NAME}
    depends_on:
      - database
      - phpmyadmin
    restart: unless-stopped
    networks:
      - wordpress-default
    ports:
      - "9001"
      - "9003"
#      - "9000"
    extra_hosts:
      - "host-gateway.docker.internal:host-gateway"

  database:
    image: mariadb:${MARIADB_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}_database
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD:-password}
      - MYSQL_USER=${DATABASE_USER:-root}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD:-password}
      - MYSQL_DATABASE=${COMPOSE_PROJECT_NAME:-wordpress}
    networks:
      - wordpress-default
    expose:
      - "3306"
    extra_hosts:
      - "host-gateway.docker.internal:host-gateway"

  phpmyadmin:
    container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION:-latest}
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
    networks:
      - wordpress-default
    expose:
      - "${PHPMYADMIN_PORT}"
    extra_hosts:
      - "host-gateway.docker.internal:host-gateway"

  # Command line interface to wordpress
  wpcli:
    container_name: ${COMPOSE_PROJECT_NAME}_wp_cli
    build: ./wpcli/
    image: wpcli
    volumes:
      - ${WORDPRESS_DATA_DIR:-./wordpress}:/var/www/html
    working_dir: /var/www/html
    networks:
      - wordpress-default
    user: "${CURRENT_UID}:${CURRENT_GID}"
    extra_hosts:
      - "host-gateway.docker.internal:host-gateway"

  # Check availability of essential services
  healthcheck:
    image: wpcli
    build: ./wpcli/
    container_name: ${COMPOSE_PROJECT_NAME}_healthcheck
    command: sh -c "/wait"
    environment:
      - WAIT_HOSTS=database:3306, webserver:80
      - WAIT_BEFORE_HOSTS=${WAIT_BEFORE_HOSTS:-30}
      - WAIT_AFTER_HOSTS=${WAIT_AFTER_HOSTS:-15}
      - WAIT_HOSTS_TIMEOUT=${WAIT_HOSTS_TIMEOUT:-300}
      - WAIT_SLEEP_INTERVAL=${WAIT_SLEEP_INTERVAL:-30}
      - WAIT_HOST_CONNECT_TIMEOUT=${WAIT_HOST_CONNECT_TIMEOUT:-30}
    networks:
      - wordpress-default
    extra_hosts:
      - "host-gateway.docker.internal:host-gateway"


volumes:
  db_data: { }